# Generated by Django 5.2 on 2025-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutable',
            name='inventory',
            field=models.SmallIntegerField(),
        ),
    ]
